language: python
python:
- 3.6
cache: pip
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
# this tests to make sure that it builds properly
- make html

# deploy if this is master
#- test $TRAVIS_BRANCH = "master" && make deploy || true
