language: python
python:
- 3.6
cache: pip
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make html
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: _build/html
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
